/API 1
http://localhost:3000/players/

###
//API 2

http://localhost:3000/players/2/

###
//API 3
PUT http://localhost:3000/players/2/
Content-Type: application/json

{
  "playerName": "Raju"
}

###
//API 4

http://localhost:3000/matches/18/

###
//API 5
http://localhost:3000/players/4/matches/

###
//API 6
http://localhost:3000/matches/4/players

###
//API 7
http://localhost:3000/players/1/playerScores